In [2]:
import pandas as pd
import numpy as np
import os

ADHD_Outcome: Type of Diagnosis (0=Other/None, 1=ADHD)

Sex_F: Sex of participant (0=Male, 1=Female)

In [3]:
# Загрузка Excel файлов 
df_cat = pd.read_excel('TRAIN_CATEGORICAL_METADATA_new.xlsx')
df_quant = pd.read_excel('TRAIN_QUANTITATIVE_METADATA_new.xlsx')
df_target = pd.read_excel('TRAINING_SOLUTIONS.xlsx')

In [4]:
df_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1213 entries, 0 to 1212
Data columns (total 10 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   participant_id                    1213 non-null   object
 1   Basic_Demos_Enroll_Year           1213 non-null   int64
 2   Basic_Demos_Study_Site            1213 non-null   int64
 3   PreInt_Demos_Fam_Child_Ethnicity  1170 non-null   float64
 4   PreInt_Demos_Fam_Child_Race       1159 non-null   float64
 5   MRI_Track_Scan_Location           1210 non-null   float64
 6   Barratt_Barratt_P1_Edu            1198 non-null   float64
 7   Barratt_Barratt_P1_Occ            1182 non-null   float64
 8   Barratt_Barratt_P2_Edu            1015 non-null   float64
 9   Barratt_Barratt_P2_Occ            991 non-null    float64
dtypes: float64(7), int64(2), object(1)
memory usage: 94.9+ KB

In [5]:
df_quant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1213 entries, 0 to 1212
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   participant_id              1213 non-null   object
 1   EHQ_EHQ_Total               1200 non-null   float64
 2   ColorVision_CV_Score        1190 non-null   float64
 3   APQ_P_APQ_P_CP              1201 non-null   float64
 4   APQ_P_APQ_P_ID              1201 non-null   float64
 5   APQ_P_APQ_P_INV             1201 non-null   float64
 6   APQ_P_APQ_P_OPD             1201 non-null   float64
 7   APQ_P_APQ_P_PM              1201 non-null   float64
 8   APQ_P_APQ_P_PP              1201 non-null   float64
 9   SDQ_SDQ_Conduct_Problems    1204 non-null   float64
 10  SDQ_SDQ_Difficulties_Total  1204 non-null   float64
 11  SDQ_SDQ_Emotional_Problems  1204 non-null   float64
 12  SDQ_SDQ_Externalizing       1204 non-null   float64
 13  SDQ_SDQ_Generating_Impact   1204 non-null   float64
 14  SDQ_SDQ_Hyperactivity       1204 non-null   float64
 15  SDQ_SDQ_Internalizing       1204 non-null   float64
 16  SDQ_SDQ_Peer_Problems       1204 non-null   float64
 17  SDQ_SDQ_Prosocial           1204 non-null   float64
 18  MRI_Track_Age_at_Scan       853 non-null    float64
dtypes: float64(18), object(1)
memory usage: 180.2+ KB

In [6]:
df_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1213 entries, 0 to 1212
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   participant_id  1213 non-null   object
 1   ADHD_Outcome    1213 non-null   int64
 2   Sex_F           1213 non-null   int64
dtypes: int64(2), object(1)
memory usage: 28.6+ KB

In [7]:
# Загрузка CSV с матрицами
df_connectome = pd.read_csv('TRAIN_FUNCTIONAL_CONNECTOME_MATRICES_new_36P_Pearson.csv')

In [8]:
df_connectome.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1213 entries, 0 to 1212
Columns: 19901 entries, participant_id to 198throw_199thcolumn
dtypes: float64(19900), object(1)
memory usage: 184.2+ MB

In [9]:
# Проверим размеры
print("Категориальные признаки:", df_cat.shape)
print("Количественные признаки:", df_quant.shape)
print("Матрицы связей:", df_connectome.shape)
print("Целевая переменная:", df_target.shape)

Категориальные признаки: (1213, 10)
Количественные признаки: (1213, 19)
Матрицы связей: (1213, 19901)
Целевая переменная: (1213, 3)

In [22]:
df.shape

(1213, 19930)

In [10]:
df_cat.columns

Index(['participant_id', 'Basic_Demos_Enroll_Year', 'Basic_Demos_Study_Site',
       'PreInt_Demos_Fam_Child_Ethnicity', 'PreInt_Demos_Fam_Child_Race',
       'MRI_Track_Scan_Location', 'Barratt_Barratt_P1_Edu',
       'Barratt_Barratt_P1_Occ', 'Barratt_Barratt_P2_Edu',
       'Barratt_Barratt_P2_Occ'],
      dtype='object')

In [17]:
# Введем переменную
common_id = 'participant_id'
# Объединяем по ID
df = df_cat.merge(df_quant, on = common_id, how = 'inner')
#df = df.merge(df_connectome, on = common_id, how = 'inner')
df = df.merge(df_target, on = common_id, how = 'inner')

print('Финальная таблица (train):', df.shape)
df.head()

Финальная таблица (train): (1213, 30)

,participant_id,Basic_Demos_Enroll_Year,Basic_Demos_Study_Site,PreInt_Demos_Fam_Child_Ethnicity,PreInt_Demos_Fam_Child_Race,MRI_Track_Scan_Location,Barratt_Barratt_P1_Edu,Barratt_Barratt_P1_Occ,Barratt_Barratt_P2_Edu,Barratt_Barratt_P2_Occ,...,SDQ_SDQ_Emotional_Problems,SDQ_SDQ_Externalizing,SDQ_SDQ_Generating_Impact,SDQ_SDQ_Hyperactivity,SDQ_SDQ_Internalizing,SDQ_SDQ_Peer_Problems,SDQ_SDQ_Prosocial,MRI_Track_Age_at_Scan,ADHD_Outcome,Sex_F
0,00aIpNTbG5uh,2019,4,1.0,0.0,3.0,21.0,45.0,NaN,NaN,...,4.0,11.0,5.0,8.0,6.0,2.0,9.0,14.274127,1,0
1,00fV0OyyoLfw,2017,1,0.0,9.0,2.0,21.0,0.0,21.0,45.0,...,4.0,13.0,5.0,8.0,7.0,3.0,8.0,NaN,1,0
2,04X1eiS79T4B,2017,1,1.0,2.0,2.0,9.0,0.0,NaN,NaN,...,7.0,10.0,10.0,7.0,14.0,7.0,7.0,13.463381,0,1
3,05ocQutkURd6,2018,1,3.0,8.0,2.0,18.0,10.0,18.0,0.0,...,0.0,3.0,0.0,3.0,2.0,2.0,6.0,9.572553,0,1
4,06YUNBA9ZRLq,2018,1,0.0,1.0,2.0,12.0,0.0,NaN,NaN,...,7.0,15.0,8.0,9.0,8.0,1.0,4.0,6.654574,1,0

In [15]:
df.to_csv("train_combined.csv", index=False)

In [11]:
# Загрузка Excel файлов для тестовых данных
df_cat_test = pd.read_excel('TEST_CATEGORICAL.xlsx')
df_quant_test = pd.read_excel('TEST_QUANTITATIVE_METADATA.xlsx')

In [12]:
# Загрузка CSV с матрицами
df_connectome_test = pd.read_csv('TEST_FUNCTIONAL_CONNECTOME_MATRICES.csv')

In [13]:
# Проверим размеры
print("Категориальные признаки:", df_cat_test.shape)
print("Количественные признаки:", df_quant_test.shape)
print("Матрицы связей:", df_connectome_test.shape)

Категориальные признаки: (304, 10)
Количественные признаки: (304, 19)
Матрицы связей: (304, 19901)

In [14]:
# Объединяем по ID
df_test = df_cat_test.merge(df_quant_test, on = common_id, how = 'inner')
#df_test = df_test.merge(df_connectome_test, on = common_id, how = 'inner')

print('Финальная таблица (train):', df_test.shape)
df_test.head()

Финальная таблица (train): (304, 28)

,participant_id,Basic_Demos_Enroll_Year,Basic_Demos_Study_Site,PreInt_Demos_Fam_Child_Ethnicity,PreInt_Demos_Fam_Child_Race,MRI_Track_Scan_Location,Barratt_Barratt_P1_Edu,Barratt_Barratt_P1_Occ,Barratt_Barratt_P2_Edu,Barratt_Barratt_P2_Occ,...,SDQ_SDQ_Conduct_Problems,SDQ_SDQ_Difficulties_Total,SDQ_SDQ_Emotional_Problems,SDQ_SDQ_Externalizing,SDQ_SDQ_Generating_Impact,SDQ_SDQ_Hyperactivity,SDQ_SDQ_Internalizing,SDQ_SDQ_Peer_Problems,SDQ_SDQ_Prosocial,MRI_Track_Age_at_Scan
0,Cfwaf5FX7jWK,2022,4,0.0,0.0,4,21.0,30.0,18.0,30.0,...,2.0,12.0,3.0,9.0,2.0,7.0,3.0,0.0,8.0,8.992813
1,vhGrzmvA3Hjq,2023,4,0.0,0.0,4,21.0,45.0,NaN,30.0,...,2.0,16.0,8.0,5.0,7.0,3.0,11.0,3.0,9.0,12.324093
2,ULliyEXjy4OV,2022,4,0.0,0.0,4,21.0,40.0,18.0,40.0,...,1.0,7.0,1.0,6.0,1.0,5.0,1.0,0.0,9.0,7.770933
3,LZfeAb1xMtql,2022,4,0.0,0.0,3,21.0,45.0,21.0,45.0,...,4.0,15.0,4.0,10.0,8.0,6.0,5.0,1.0,6.0,9.304814
4,EnFOUv0YK1RG,2022,4,2.0,0.0,4,18.0,0.0,21.0,45.0,...,2.0,18.0,6.0,12.0,5.0,10.0,6.0,0.0,10.0,8.261350

In [15]:
df_test.to_csv("test_combined.csv", index=False)